---
# 04-template-config.yml
# Responsável: PREENCHER SEU NOME
# Descrição: Renderização de config via template Jinja2
#
# Execução:
#   ansible-playbook -i ../inventario/hosts.ini 04-template-config.yml

- name: PREENCHER
  hosts: all
  become: yes

  tasks:
    - name: PREENCHER
      ansible.builtin.debug:
        msg: "substituir por tasks reais"
