# Inventário de exemplo do Grupo 4
# Uso: ansible-playbook -i inventario/hosts.ini exemplos/03-playbook-nginx.yml

[local]
localhost ansible_connection=local

[webservers]
# web01 ansible_host=192.168.56.10 ansible_user=vagrant

[all:vars]
ansible_python_interpreter=/usr/bin/python3
